#!/usr/bin/env bash
# UEV-ERP → Hostinger deploy via PuTTY pscp (replaces OpenSSH scp)
set -uo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
SSH="u129919172@92.113.18.239"
PORT="65002"
WEB="domains/sr-ue-varna.com/public_html"
KEY="SHA256:GUsIM5l8gUqw77PsnGpLF/m9SUPUzIbZFL1ZtpWq4zk"
PSCP="C:/Program Files/PuTTY/pscp.exe"
PLINK="C:/Program Files/PuTTY/plink.exe"

if [ -z "${SSH_PASS:-}" ]; then
  echo "ERROR: SSH_PASS env var required"; exit 1
fi

DRY=true
for arg in "$@"; do [ "$arg" = "--push" ] && DRY=false; done
cd "$REPO"

# Same allow-list as deploy.sh
FILES=(
  ".htaccess"
  "index.html"
  "manifest.webmanifest"
  "manifest.json"
  "sw.js"
  "version.json"
  "styles.css"
  "styles-responsive.css"
  "css/uev.css" "css/uev-dark-mode.css"
  "js/app.js" "js/assets.js" "js/competitions.js" "js/compliance.js"
  "js/components.js" "js/config.js" "js/config-secrets.js"
  "js/core-bundle.js" "js/data-layer.js" "js/dashboard.js"
  "js/documents.js" "js/doc-viewer.js" "js/forms-admin.js"
  "js/hostinger-config.js" "js/hostinger-config-laravel.js"
  "js/i18n.js" "js/library-deposits.js" "js/main.js"
  "js/ministry-reports.js" "js/proposal-extras.js"
  "js/features/mobile/installPrompt.js"
  "js/public-results.js" "js/reviews.js" "js/router.js"
  "js/search.js" "js/settings.js" "js/utils.js"
  "js/veda.js" "js/veda-chat.js"
  "js/views-bundle.js"
  "js/services/api.js" "js/services/cache.js" "js/services/documents.js"
  "js/services/storage.js" "js/services/sync.js"
  "js/processors/events.js" "js/processors/search.js" "js/processors/validator.js"
  "js/vendor/mammoth.browser.min.js" "js/vendor/pdf.min.js"
  "js/vendor/pdf.worker.min.js" "js/vendor/xlsx.full.min.js"
  "assets/admin-structure.json" "assets/science-logo.png"
  "assets/uev-logo.jpg" "assets/uev-social-logo.png"
  "assets/yonkoai-logo-dark.svg" "assets/yonkoai-logo-transparent.svg"
  "assets/yonkoai-logo-transparent-medium.png"
  "js/features/proposal-wizard/proposal-wizard.css"
  "js/features/proposal-wizard/proposal-wizard-bundle.js"
  "js/features/proposal-wizard/WizardShell.js"
  "js/features/proposal-wizard/useAutosave.js"
  "js/features/proposal-wizard/useWizardState.js"
  "js/features/proposal-wizard/api/proposalsApi.js"
  "js/features/proposal-wizard/api/types.js"
  "js/features/proposal-wizard/shared/AutosaveIndicator.js"
  "js/features/proposal-wizard/shared/ConfirmCloseDialog.js"
  "js/features/proposal-wizard/shared/ConflictResolutionDialog.js"
  "js/features/proposal-wizard/shared/DocumentCard.js"
  "js/features/proposal-wizard/shared/InlineValidationSummary.js"
  "js/features/proposal-wizard/shared/StatusBadge.js"
  "js/features/proposal-wizard/shared/StepIndicator.js"
  "js/features/proposal-wizard/shared/types.js"
  "js/features/proposal-wizard/shared/useAutosave.js"
  "js/features/proposal-wizard/shared/useWizardState.js"
  "js/features/proposal-wizard/steps/Step1BasicInfo/Step1BasicInfo.js"
  "js/features/proposal-wizard/steps/Step1BasicInfo/step1.schema.js"
  "js/features/proposal-wizard/steps/Step2Documents/Step2Documents.js"
  "js/features/proposal-wizard/steps/Step2Documents/step2.schema.js"
  "js/features/proposal-wizard/steps/Step3Budget/Step3Budget.js"
  "js/features/proposal-wizard/steps/Step3Budget/step3.schema.js"
  "js/features/admin/reviewer-publications.js"
  "js/features/admin/reviewer-publications-modal.js"
  "js/features/staff/staff-publications.js"
  "js/features/staff/orcid-connection.js"
  "js/features/staff/orcid-config.js"
  "js/features/doc-stream/DocStreamClient.js"
  "js/features/doc-stream/DocStreamEditor.css"
  "js/features/doc-stream/DocStreamEditor.js"
  "js/features/proposal-wizard/admin/WizardAdminDashboard.js"
  "js/features/proposal-wizard/admin/WizardDashboardWidget.js"
  "js/features/proposal-wizard/admin/WizardPublicView.js"
  "js/features/proposal-wizard/api/wizardAdminApi.js"
  "js/features/proposal-wizard/config/document-requirements.js"
  "js/features/proposal-wizard/config/program-template-folders.js"
  "js/features/proposal-wizard/shared/SavePointDialog.js"
  "js/features/proposal-wizard/shared/browserCompat.js"
  "js/features/proposal-wizard/shared/i18n.js"
  "js/features/proposal-wizard/shared/useAccessibility.js"
  "js/features/proposal-wizard/shared/useCsvImport.js"
  "js/features/proposal-wizard/shared/useEmailNotification.js"
  "js/features/proposal-wizard/shared/useSavePoints.js"
  "js/features/proposal-wizard/hooks/useWizardNavigation.js"
  "js/features/proposal-wizard/store/wizardStore.js"
  "js/features/proposal-wizard/utils/validation.js"
  "js/features/proposal-wizard/proposal-wizard-admin.css"
  "js/features/proposal-wizard/config/TemplatesSection.js"
  "js/features/proposal-wizard/config/budget-rules.js"
  "js/features/proposal-wizard/steps/Step2Documents/Step2DocumentPreview.js"
  "js/features/proposal-wizard/steps/Step2Documents/Step2RefereeCheck.js"
  "js/features/proposal-wizard/steps/Step4Review/Step4Review.js"
  "js/features/proposal-wizard/shared/AutosaveIndicator.js"
  "js/features/proposal-wizard/shared/ConfirmCloseDialog.js"
  "js/features/proposal-wizard/shared/ConflictResolutionDialog.js"
  "js/features/proposal-wizard/shared/DocumentCard.js"
  "js/features/proposal-wizard/shared/InlineValidationSummary.js"
  "js/features/proposal-wizard/shared/StatusBadge.js"
  "js/features/proposal-wizard/shared/StepIndicator.js"
  "js/features/proposal-wizard/shared/types.js"
  "js/features/proposal-wizard/shared/useAutosave.js"
  "js/features/proposal-wizard/shared/useWizardState.js"
  "js/features/proposal-wizard/WizardShell.js"
  "js/features/proposal-wizard/useAutosave.js"
  "js/features/proposal-wizard/useWizardState.js"
  "js/features/proposal-wizard/proposal-wizard.css"
  "js/features/proposal-wizard/proposal-wizard-bundle.js"
  "js/features/proposal-wizard/proposal-wizard-admin.css"
  "js/features/proposal-wizard/admin/WizardAdminDashboard.js"
  "js/features/proposal-wizard/admin/WizardDashboardWidget.js"
  "js/features/proposal-wizard/admin/WizardPublicView.js"
  "js/features/proposal-wizard/api/proposalsApi.js"
  "js/features/proposal-wizard/api/types.js"
  "js/features/proposal-wizard/api/wizardAdminApi.js"
  "js/features/proposal-wizard/components/WizardShell.js"
  "js/features/proposal-wizard/config/TemplatesSection.js"
  "js/features/proposal-wizard/config/budget-rules.js"
  "js/features/proposal-wizard/config/document-requirements.js"
  "js/features/proposal-wizard/config/program-template-folders.js"
  "js/features/proposal-wizard/hooks/useWizardNavigation.js"
  "js/features/proposal-wizard/shared/AutosaveIndicator.js"
  "js/features/proposal-wizard/shared/browserCompat.js"
  "js/features/proposal-wizard/shared/ConfirmCloseDialog.js"
  "js/features/proposal-wizard/shared/ConflictResolutionDialog.js"
  "js/features/proposal-wizard/shared/DocumentCard.js"
  "js/features/proposal-wizard/shared/InlineValidationSummary.js"
  "js/features/proposal-wizard/shared/SavePointDialog.js"
  "js/features/proposal-wizard/shared/StatusBadge.js"
  "js/features/proposal-wizard/shared/StepIndicator.js"
  "js/features/proposal-wizard/shared/i18n.js"
  "js/features/proposal-wizard/shared/types.js"
  "js/features/proposal-wizard/shared/useAccessibility.js"
  "js/features/proposal-wizard/shared/useAutosave.js"
  "js/features/proposal-wizard/shared/useCsvImport.js"
  "js/features/proposal-wizard/shared/useEmailNotification.js"
  "js/features/proposal-wizard/shared/useSavePoints.js"
  "js/features/proposal-wizard/shared/useWizardState.js"
  "js/features/proposal-wizard/steps/Step1BasicInfo/Step1BasicInfo.js"
  "js/features/proposal-wizard/steps/Step1BasicInfo/step1.schema.js"
  "js/features/proposal-wizard/steps/Step2Documents/Step2DocumentPreview.js"
  "js/features/proposal-wizard/steps/Step2Documents/Step2Documents.js"
  "js/features/proposal-wizard/steps/Step2Documents/Step2RefereeCheck.js"
  "js/features/proposal-wizard/steps/Step2Documents/step2.schema.js"
  "js/features/proposal-wizard/steps/Step3Budget/Step3Budget.js"
  "js/features/proposal-wizard/steps/Step3Budget/step3.schema.js"
  "js/features/proposal-wizard/steps/Step4Review/Step4Review.js"
  "js/features/proposal-wizard/store/wizardStore.js"
  "js/features/proposal-wizard/useAutosave.js"
  "js/features/proposal-wizard/useWizardState.js"
  "js/features/proposal-wizard/utils/validation.js"
  "js/admin-manager-view.js"
  "js/app.js.test"
  "js/browserCompat.js"
  "js/budget-rules.js"
  "js/cache.js"
  "js/cache-util.js"
  "js/compliance.js"
  "js/config.js"
  "js/config-secrets.example.js"
  "js/core-bundle.js"
  "js/dashboard.js"
  "js/data-layer.js"
  "js/db-data-viewer.js"
  "js/document-requirements.js"
  "js/doc-viewer.js"
  "js/events.js"
  "js/fetchProposal.js"
  "js/fetchProposals.js"
  "js/forms-admin.js"
  "js/hostinger-config.js"
  "js/hostinger-config-laravel.js"
  "js/i18n.js"
  "js/index.js"
  "js/InlineValidationSummary.js"
  "js/installPrompt.js"
  "js/library-deposits.js"
  "js/main.js"
  "js/ministry-reports.js"
  "js/oidc.js"
  "js/orcid-config.js"
  "js/orcid-connection.js"
  "js/program-template-folders.js"
  "js/proposal-extras.js"
  "js/proposalsApi.js"
  "js/proposal-wizard-bundle.js"
  "js/public-results.js"
  "js/reviewer-publications.js"
  "js/reviewer-publications-modal.js"
  "js/reviews.js"
  "js/router.js"
  "js/SavePointDialog.js"
  "js/search.js"
  "js/services/api.js"
  "js/services/cache.js"
  "js/services/documents.js"
  "js/services/index.js"
  "js/services/oidc.js"
  "js/services/storage.js"
  "js/services/sync.js"
  "js/settings.js"
  "js/staff-publications.js"
  "js/StatusBadge.js"
  "js/step1.schema.js"
  "js/Step1BasicInfo.js"
  "js/step2.schema.js"
  "js/Step2DocumentPreview.js"
  "js/Step2Documents.js"
  "js/Step2RefereeCheck.js"
  "js/step3.schema.js"
  "js/Step3Budget.js"
  "js/Step4Review.js"
  "js/StepIndicator.js"
  "js/storage.js"
  "js/submitProposal.js"
  "js/sw.js"
  "js/sync.js"
  "js/TemplatesSection.js"
  "js/types.js"
  "js/useAccessibility.js"
  "js/useAutosave.js"
  "js/useCsvImport.js"
  "js/useEmailNotification.js"
  "js/useSavePoints.js"
  "js/useWizardState.js"
  "js/utils.js"
  "js/validator.js"
  "js/veda.js"
  "js/veda-chat.js"
  "js/vendor/mammoth.browser.min.js"
  "js/vendor/pdf.min.js"
  "js/vendor/pdf.worker.min.js"
  "js/vendor/xlsx.full.min.js"
  "js/views-bundle.js"
  "js/wizardAdminApi.js"
  "js/WizardShell.js"
  "app.js"
  "config.php"
  "action_map.php"
  "health.php"
  "healthz.php"
  "index.php"
  "orcid_callback.php"
  "orcid_oauth.php"
  "orcid-config.js"
  "orcid-connection.js"
  "reviewer-publications.js"
  "reviewer-publications-modal.js"
  "robots.txt"
  "security-headers.php"
  "serve-js.php"
  "sql_service.php"
  "staff-publications.js"
  "styles-modern.css"
  "uev.css"
  "veda_handlers.php"
  "views-bundle.js"
)

echo "=== Deploy: ${#FILES[@]} files ==="
echo "Mode: $([ "$DRY" = true ] && echo "DRY RUN" || echo "LIVE PUSH")"

OK=0
FAIL=0
for f in "${FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "  [skip] $f (not found)"
    continue
  fi
  if [ "$DRY" = true ]; then
    echo "  [dry] $f"
  else
    output=$("$PSCP" -P "$PORT" -pw "$SSH_PASS" -batch -hostkey "$KEY" "$f" "$SSH:$WEB/$f" 2>&1)
    if echo "$output" | grep -q "100%"; then
      OK=$((OK+1))
    else
      echo "  [FAIL] $f: $output"
      FAIL=$((FAIL+1))
    fi
  fi
done

if [ "$DRY" = false ]; then
  echo ""
  echo "=== Uploaded: $OK ok, $FAIL failed ==="
  echo "=== Clearing OPcache ==="
  "$PLINK" -P "$PORT" -pw "$SSH_PASS" -hostkey "$KEY" "$SSH" "cd $WEB && php -r 'opcache_reset();'" 2>&1
  echo ""
  echo "=== Verifying live version ==="
  sleep 2
  curl -s "https://sr-ue-varna.com/version.json"
  echo ""
fi

echo "=== Done ==="
